import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  BookOpen,
  Play,
  Pause,
  Volume2,
} from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { useEffect, forwardRef } from "react";
import { useAudioPlayer } from "@/hooks/useAudioPlayer";

const StoryCard = forwardRef(function StoryCard(
  {
    loading,
    story,
    storyRef,
    onQuizStart,
  },
  ref
) {
  const {
    generateAndPlayAudio,
    pauseAudio,
    resumeAudio,
    resetAutoGenerated,
    isPlaying,
    isPaused,
    isGenerating,
    audioGenerated,
  } = useAudioPlayer();

  useEffect(() => {
    if (story) {
      resetAutoGenerated();
    }
  }, [story, resetAutoGenerated]);

  useEffect(() => {
    if (onQuizStart) {
      onQuizStart(() => {
        if (isPlaying) {
          pauseAudio();
        }
      });
    }
  }, [onQuizStart, isPlaying, pauseAudio]);

  const handlePlayPause = async () => {
    if (!story) return;

    try {
      if (!isPlaying && !isPaused) {
        await generateAndPlayAudio(story, false);
      } else if (isPaused) {
        await resumeAudio();
      } else {
        pauseAudio();
      }
    } catch (error) {
      console.error("Error handling play/pause:", error);
    }
  };

  const extractTitle = (storyText) => {
    if (!storyText) return { title: null, remainingContent: storyText };
    const lines = storyText.split('\n');
    let titleLine = null;
    let titleIndex = -1;

    for (let i = 0; i < lines.length; i++) {
      const trimmedLine = lines[i].trim();
      if (trimmedLine.startsWith('# ')) {
        titleLine = trimmedLine.substring(2).trim();
        titleIndex = i;
        break;
      }
    }

    if (titleLine !== null) {
      const remainingContent = [
        ...lines.slice(0, titleIndex),
        ...lines.slice(titleIndex + 1)
      ].join('\n').trim();
      return { title: titleLine, remainingContent };
    }

    return { title: null, remainingContent: storyText };
  };

  const { title: storyTitle, remainingContent: storyContent } = extractTitle(story);

  if (loading) {
    return (
      <Card
        ref={storyRef}
        className="overflow-hidden border-border/50 shadow-2xl bg-card/80 backdrop-blur-xl animate-fade-in-up"
      >
        <div className="relative min-h-[400px] flex flex-col items-center justify-center py-12 overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-secondary/5 to-primary/10 animate-pulse"></div>

          <div className="absolute inset-0 overflow-hidden pointer-events-none">
            <div className="absolute top-8 left-8 w-16 h-16 rounded-full bg-primary/10 animate-bounce" style={{ animationDelay: '0s', animationDuration: '3s' }}></div>
            <div className="absolute top-16 right-12 w-10 h-10 rounded-full bg-secondary/10 animate-bounce" style={{ animationDelay: '0.5s', animationDuration: '2.5s' }}></div>
            <div className="absolute bottom-16 left-16 w-12 h-12 rounded-full bg-primary/10 animate-bounce" style={{ animationDelay: '1s', animationDuration: '3.5s' }}></div>
            <div className="absolute bottom-8 right-8 w-8 h-8 rounded-full bg-secondary/10 animate-bounce" style={{ animationDelay: '1.5s', animationDuration: '2s' }}></div>
          </div>

          <div className="relative z-10 flex flex-col items-center text-center px-6">
            <div className="relative mb-6">
              <div className="absolute inset-0 bg-primary/20 rounded-full blur-xl animate-pulse"></div>
              <div className="relative p-6 bg-gradient-to-br from-primary to-primary/80 rounded-2xl shadow-2xl">
                <BookOpen className="w-12 h-12 text-primary-foreground animate-pulse" />
              </div>
            </div>

            <h3 className="text-2xl font-bold text-foreground mb-2">
              正在创作您的专属故事
            </h3>
            <p className="text-muted-foreground mb-6 max-w-sm">
              AI 正在根据您的选择生成个性化英语学习内容，请稍候...
            </p>

            <div className="w-64 h-2 bg-border/50 rounded-full overflow-hidden mb-4">
              <div className="h-full bg-gradient-to-r from-primary via-secondary to-primary bg-[length:200%_100%] animate-pulse rounded-full"></div>
            </div>

            <div className="w-full max-w-md mt-8 space-y-3 opacity-40">
              <div className="h-6 bg-gradient-to-r from-border via-border/60 to-border rounded-lg animate-pulse w-3/4 mx-auto"></div>
              <div className="h-4 bg-gradient-to-r from-border via-border/60 to-border rounded-lg animate-pulse w-full"></div>
              <div className="h-4 bg-gradient-to-r from-border via-border/60 to-border rounded-lg animate-pulse w-5/6"></div>
              <div className="h-4 bg-gradient-to-r from-border via-border/60 to-border rounded-lg animate-pulse w-4/5"></div>
            </div>
          </div>
        </div>
      </Card>
    );
  }

  return (
    <Card
      ref={storyRef}
      className="overflow-hidden border-border/50 shadow-2xl bg-card/80 backdrop-blur-xl animate-fade-in-up"
    >
      {/* Header */}
      <div className="px-5 py-4 sm:px-6 sm:py-4 border-b border-border/50 bg-muted/20">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-primary text-primary-foreground shadow-lg">
              <BookOpen className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-card-foreground">
                阅读文章
              </h2>
              <p className="text-xs text-muted-foreground">
                仔细阅读下面的故事
              </p>
            </div>
          </div>

          {story && (
            <Button
              onClick={handlePlayPause}
              variant="outline"
              size="sm"
              className={`flex items-center gap-2 transition-all shadow-sm active:scale-95 rounded-xl ${audioGenerated ? "" : "opacity-60"}`}
              disabled={isGenerating}
              aria-label={
                isPaused ? "继续朗读" : isPlaying ? "暂停朗读" : "开始朗读"
              }
            >
              {isGenerating ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-current"></div>
                  <span className="text-sm hidden sm:inline">生成中</span>
                </>
              ) : isPlaying ? (
                isPaused ? (
                  <>
                    <Play className="w-4 h-4" />
                    <span className="text-sm font-medium hidden sm:inline">继续</span>
                  </>
                ) : (
                  <>
                    <Pause className="w-4 h-4" />
                    <span className="text-sm font-medium hidden sm:inline">暂停</span>
                  </>
                )
              ) : (
                <>
                  <Volume2 className="w-4 h-4" />
                  <span className="text-sm font-medium hidden sm:inline">朗读</span>
                </>
              )}
            </Button>
          )}
        </div>
      </div>

      {/* Content */}
      <CardContent className="px-5 py-4 sm:px-6 sm:py-5">
        {/* Title */}
        {storyTitle && (
          <h1 className="text-2xl sm:text-3xl font-extrabold mb-4 bg-clip-text text-transparent bg-gradient-to-r from-primary to-secondary leading-tight">
            {storyTitle}
          </h1>
        )}

        {/* Story Content */}
        <div className="prose prose-slate dark:prose-invert max-w-none">
          <ReactMarkdown
            remarkPlugins={[remarkGfm]}
            components={{
              p: ({ node, ...props }) => (
                <p className="mt-4 first:mt-0 leading-relaxed text-base sm:text-lg" {...props} />
              ),
              h1: ({ node, ...props }) => (
                <h1 className="text-2xl sm:text-3xl font-extrabold mt-0 mb-6 bg-clip-text text-transparent bg-gradient-to-r from-primary to-secondary" {...props} />
              ),
              h2: ({ node, ...props }) => (
                <h2 className="text-xl sm:text-2xl font-bold mt-8 mb-4 border-b pb-2" {...props} />
              ),
              li: ({ node, ...props }) => (
                <li className="ml-6 list-disc mb-2" {...props} />
              ),
            }}
          >
            {storyContent}
          </ReactMarkdown>
        </div>
      </CardContent>
    </Card>
  );
});

StoryCard.displayName = "StoryCard";

export default StoryCard;
