import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  BookOpen,
  Image as ImageIcon,
  Eye,
  EyeOff,
  Play,
  Pause,
  Volume2,
  X as CloseIcon,
} from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { useRouter } from "next/navigation";
import { useState, useEffect, useRef, forwardRef } from "react";
import { createPortal } from "react-dom";
import { useAudioPlayer } from "@/hooks/useAudioPlayer";

const StoryCard = forwardRef(function StoryCard(
  {
    loading,
    story,
    user,
    imageLoading,
    imageError,
    generatedImage,
    storyRef,
    onQuizStart,
  },
  ref
) {
  const router = useRouter();
  const [showImage, setShowImage] = useState(true);
  const [isPreviewOpen, setIsPreviewOpen] = useState(false);

  // Use the new audio player hook
  const {
    generateAndPlayAudio,
    pauseAudio,
    resumeAudio,
    resetAutoGenerated,
    isPlaying,
    isPaused,
    isGenerating,
    audioGenerated,
    autoGenerated,
  } = useAudioPlayer();

  // Clean up audio when component unmounts or story changes
  useEffect(() => {
    // Reset audio state when story changes
    if (story) {
      // Reset auto-generated flag when a new story is loaded
      resetAutoGenerated();
      // Audio will be generated automatically when story is loaded
    }
  }, [story, resetAutoGenerated]);

  // Reset showImage to true when a new image is generated
  useEffect(() => {
    if (generatedImage) {
      setShowImage(true);
    }
  }, [generatedImage]);

  // Expose stop function to parent component
  useEffect(() => {
    if (onQuizStart) {
      onQuizStart(() => {
        // Stop any playing audio
        if (isPlaying) {
          pauseAudio();
        }
      });
    }
  }, [onQuizStart, isPlaying, pauseAudio]);

  // Handle play/pause functionality
  const handlePlayPause = async () => {
    if (!story) return;

    try {
      if (!isPlaying && !isPaused) {
        // Start generating and playing audio (manual generation)
        await generateAndPlayAudio(story, false);
      } else if (isPaused) {
        // Resume playing
        await resumeAudio();
      } else {
        // Pause playing
        pauseAudio();
      }
    } catch (error) {
      console.error("Error handling play/pause:", error);
      // You could add a toast notification here to inform the user
    }
  };

  // Story Header Component
  const StoryHeader = ({ hoverEffect = false }) => (
    <div className="relative overflow-hidden rounded-t-xl transition-all duration-500 p-6">
      <div className="relative z-10 flex items-end justify-between h-full">
        <div className="flex items-center gap-3">
          <div
            className={`p-3 rounded-xl bg-primary text-primary-foreground shadow-lg transition-transform duration-300 ${hoverEffect ? "group-hover:scale-110" : ""}`}
          >
            <BookOpen className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-card-foreground">
              阅读文章
            </h2>
            <div className="text-sm flex items-center text-muted-foreground">
              {loading && (
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-primary mr-2"></div>
              )}
              {loading ? "AI正在生成故事，请稍候..." : "仔细阅读下面的故事"}
              {!user && !loading && (
                <span className="ml-2 text-amber-500 font-bold hidden sm:inline">
                  (登录解锁AI绘图)
                </span>
              )}
            </div>
          </div>
        </div>

        {/* Text-to-Speech Button */}
        {!loading && story && (
          <Button
            onClick={handlePlayPause}
            variant="outline"
            size="sm"
            className={`flex items-center gap-2 transition-all shadow-md active:scale-95 ${audioGenerated ? "" : "opacity-60"}`}
            disabled={isGenerating}
            aria-label={
              isPaused ? "继续朗读" : isPlaying ? "暂停朗读" : "开始朗读"
            }
          >
            {isGenerating ? (
              <>
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-current"></div>
                <span className="text-sm">AI语音生成中</span>
              </>
            ) : isPlaying ? (
              isPaused ? (
                <>
                  <Play className="w-4 h-4" />
                  <span className="text-sm font-bold">继续</span>
                </>
              ) : (
                <>
                  <Pause className="w-4 h-4" />
                  <span className="text-sm font-bold">暂停</span>
                </>
              )
            ) : (
              <>
                <Volume2 className="w-4 h-4" />
                <span className="text-sm font-bold">朗读</span>
              </>
            )}
          </Button>
        )}
      </div>
    </div>
  );

  // Story Content Component
  const StoryContent = ({ storyTitle, storyContent }) => {
    if (loading) {
      return (
        <div className="relative min-h-[400px] flex flex-col items-center justify-center py-12 overflow-hidden">
          {/* Animated gradient background */}
          <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-secondary/5 to-primary/10 animate-pulse"></div>

          {/* Floating decorative elements */}
          <div className="absolute inset-0 overflow-hidden pointer-events-none">
            <div className="absolute top-8 left-8 w-16 h-16 rounded-full bg-primary/10 animate-bounce" style={{ animationDelay: '0s', animationDuration: '3s' }}></div>
            <div className="absolute top-16 right-12 w-10 h-10 rounded-full bg-secondary/10 animate-bounce" style={{ animationDelay: '0.5s', animationDuration: '2.5s' }}></div>
            <div className="absolute bottom-16 left-16 w-12 h-12 rounded-full bg-primary/10 animate-bounce" style={{ animationDelay: '1s', animationDuration: '3.5s' }}></div>
            <div className="absolute bottom-8 right-8 w-8 h-8 rounded-full bg-secondary/10 animate-bounce" style={{ animationDelay: '1.5s', animationDuration: '2s' }}></div>
          </div>

          {/* Main loading content */}
          <div className="relative z-10 flex flex-col items-center text-center px-6">
            {/* Animated book icon */}
            <div className="relative mb-6">
              <div className="absolute inset-0 bg-primary/20 rounded-full blur-xl animate-pulse"></div>
              <div className="relative p-6 bg-gradient-to-br from-primary to-primary/80 rounded-2xl shadow-2xl">
                <BookOpen className="w-12 h-12 text-primary-foreground animate-pulse" />
              </div>
            </div>

            {/* Loading text */}
            <h3 className="text-2xl font-bold text-foreground mb-2">
              正在创作您的专属故事
            </h3>
            <p className="text-muted-foreground mb-6 max-w-sm">
              AI 正在根据您的选择生成个性化英语学习内容，请稍候...
            </p>

            {/* Animated progress bar */}
            <div className="w-64 h-2 bg-border/50 rounded-full overflow-hidden mb-4">
              <div className="h-full bg-gradient-to-r from-primary via-secondary to-primary bg-[length:200%_100%] animate-pulse rounded-full"></div>
            </div>

            {/* Decorative skeleton preview */}
            <div className="w-full max-w-md mt-8 space-y-3 opacity-40">
              <div className="h-6 bg-gradient-to-r from-border via-border/60 to-border rounded-lg animate-pulse w-3/4 mx-auto"></div>
              <div className="h-4 bg-gradient-to-r from-border via-border/60 to-border rounded-lg animate-pulse w-full"></div>
              <div className="h-4 bg-gradient-to-r from-border via-border/60 to-border rounded-lg animate-pulse w-5/6"></div>
              <div className="h-4 bg-gradient-to-r from-border via-border/60 to-border rounded-lg animate-pulse w-4/5"></div>
            </div>
          </div>
        </div>
      );
    }

    return (
      <>
        {/* Title without image background (when image is hidden or not available) */}
        {storyTitle && (!generatedImage || !showImage) && (
          <h1 className="text-3xl font-extrabold mt-0 mb-6 bg-clip-text text-transparent bg-gradient-to-r from-primary to-secondary">
            {storyTitle}
          </h1>
        )}

        {/* Remaining content */}
        <div className="prose prose-slate dark:prose-invert max-w-none">
          <ReactMarkdown
            remarkPlugins={[remarkGfm]}
            components={{
              p: ({ node, ...props }) => <p className="mt-4 leading-relaxed text-lg" {...props} />,
              h1: ({ node, ...props }) => (
                <h1 className="text-3xl font-extrabold mt-0 mb-6 bg-clip-text text-transparent bg-gradient-to-r from-primary to-secondary" {...props} />
              ),
              h2: ({ node, ...props }) => (
                <h2 className="text-2xl font-bold mt-8 mb-4 border-b pb-2" {...props} />
              ),
              li: ({ node, ...props }) => (
                <li className="ml-6 list-disc mb-2" {...props} />
              ),
            }}
          >
            {storyContent}
          </ReactMarkdown>
        </div>
      </>
    );
  };

  // Image Preview Modal Component - rendered via portal to escape stacking context
  const ImagePreviewModal = () => {
    if (typeof document === 'undefined') return null;

    return createPortal(
      <div
        className="fixed inset-0 bg-black/90 backdrop-blur-md flex items-center justify-center z-[9999] p-4"
        onClick={() => setIsPreviewOpen(false)}
        role="dialog"
        aria-modal="true"
        aria-label="Image Preview"
      >
        <div
          className="relative max-w-5xl max-h-[95vh] animate-in zoom-in-95 duration-300"
          onClick={(e) => e.stopPropagation()}
        >
          <img
            src={generatedImage}
            alt="Full size"
            className="object-contain w-auto h-auto max-w-full max-h-[90vh] rounded-xl shadow-2xl border-4 border-white/10"
          />
          <button
            onClick={() => setIsPreviewOpen(false)}
            className="absolute -top-4 -right-4 bg-white text-black p-2 rounded-full shadow-xl hover:bg-gray-200 transition-colors z-10"
          >
            <CloseIcon className="w-6 h-6" />
          </button>
        </div>
      </div>,
      document.body
    );
  };

  // Control Buttons (Toggle Image)
  const ActionControls = () => (
    <div className="flex items-center justify-between px-6 py-3 bg-muted/30 border-t border-border/50">
      <div className="flex items-center gap-2">
        <span className="text-xs font-semibold text-muted-foreground uppercase tracking-widest">
          显示设置
        </span>
      </div>
      <div className="flex items-center gap-2">
        {generatedImage && (
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setShowImage(!showImage)}
            className="flex items-center gap-2 text-muted-foreground hover:text-primary"
          >
            {showImage ? (
              <>
                <EyeOff className="w-4 h-4" />
                <span>隐藏封面</span>
              </>
            ) : (
              <>
                <Eye className="w-4 h-4" />
                <span>显示封面</span>
              </>
            )}
          </Button>
        )}
        {generatedImage && showImage && (
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setIsPreviewOpen(true)}
            className="flex items-center gap-2 text-muted-foreground hover:text-primary"
          >
            <ImageIcon className="w-4 h-4" />
            <span>查看大图</span>
          </Button>
        )}
      </div>
    </div>
  );

  // Extract title from story (first line that starts with #)
  const extractTitle = (storyText) => {
    if (!storyText) return { title: null, remainingContent: storyText };
    const lines = storyText.split('\n');
    let titleLine = null;
    let titleIndex = -1;

    for (let i = 0; i < lines.length; i++) {
      const trimmedLine = lines[i].trim();
      if (trimmedLine.startsWith('# ')) {
        titleLine = trimmedLine.substring(2).trim();
        titleIndex = i;
        break;
      }
    }

    if (titleLine !== null) {
      const remainingContent = [
        ...lines.slice(0, titleIndex),
        ...lines.slice(titleIndex + 1)
      ].join('\n').trim();
      return { title: titleLine, remainingContent };
    }

    return { title: null, remainingContent: storyText };
  };

  const { title: storyTitle, remainingContent: storyContent } = extractTitle(story);

  return (
    <>
      {isPreviewOpen && <ImagePreviewModal />}

      {/* Title with Image Background - Outside the Card */}
      {generatedImage && showImage && (
        <div className="relative overflow-hidden rounded-2xl mb-6 group min-h-[200px] sm:min-h-[280px] shadow-2xl">
          <img
            src={generatedImage}
            alt="Story background"
            className="absolute inset-0 w-full h-full object-cover transform scale-105 group-hover:scale-110 transition-transform duration-700"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/40 to-transparent"></div>
          {storyTitle && (
            <div className="absolute inset-0 z-10 px-6 sm:px-10 py-8 flex items-end">
              <h1 className="text-3xl sm:text-4xl font-extrabold text-white drop-shadow-lg">
                {storyTitle}
              </h1>
            </div>
          )}
        </div>
      )}

      {/* Article Container */}
      <Card
        ref={storyRef}
        className="overflow-hidden border-border/60 shadow-2xl bg-card/50 backdrop-blur-xl animate-fade-in-up"
      >
        <StoryHeader hoverEffect={true} />
        <ActionControls />
        <CardContent className="p-6 sm:p-10">
          <StoryContent storyTitle={storyTitle} storyContent={storyContent} />
        </CardContent>
      </Card>
    </>
  );
});

StoryCard.displayName = "StoryCard";

export default StoryCard;
