import { useState, useCallback, useRef } from "react";

// Helper to decode base64 string to Uint8Array
function decode(base64) {
  const binaryString = window.atob(base64);
  const len = binaryString.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}

// Helper to decode raw PCM data into an AudioBuffer
async function decodeAudioData(data, ctx, sampleRate, numChannels) {
  const dataInt16 = new Int16Array(data.buffer);
  const frameCount = dataInt16.length / numChannels;
  const buffer = ctx.createBuffer(numChannels, frameCount, sampleRate);

  for (let channel = 0; channel < numChannels; channel++) {
    const channelData = buffer.getChannelData(channel);
    for (let i = 0; i < frameCount; i++) {
      channelData[i] = dataInt16[i * numChannels + channel] / 32768.0;
    }
  }
  return buffer;
}

// Clean markdown content for speech synthesis
const cleanMarkdownForSpeech = (text) => {
  if (!text) return "";

  return (
    text
      // Remove markdown headers (# ## ### etc.)
      .replace(/^#{1,6}\s+/gm, "")
      // Remove bold/italic markers (** * __ _)
      .replace(/\*\*(.*?)\*\*/g, "$1")
      .replace(/\*(.*?)\*/g, "$1")
      .replace(/__(.*?)__/g, "$1")
      .replace(/_(.*?)_/g, "$1")
      // Remove links [text](url) -> keep only text
      .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
      // Remove inline code `code`
      .replace(/`([^`]+)`/g, "$1")
      // Remove code blocks
      .replace(/```[\s\S]*?```/g, "")
      // Remove image markdown ![alt](url)
      .replace(/!\[([^\]]*)\]\([^)]+\)/g, "")
      // Remove blockquotes >
      .replace(/^>\s+/gm, "")
      // Remove lists markers (1. 2. 3. and - * +)
      .replace(/^\d+\.\s+/gm, "")
      .replace(/^[-*+]\s+/gm, "")
      // Remove horizontal rules
      .replace(/^---+$/gm, "")
      // Remove extra line breaks but keep paragraph breaks
      .replace(/\n{3,}/g, "\n\n")
      // Remove any remaining markdown syntax patterns
      .replace(/[#*`_~\[\]()]/g, "")
      .trim()
  );
};

export const useAudioPlayer = () => {
  const audioContextRef = useRef(null);
  const sourceRef = useRef(null);
  const audioBufferRef = useRef(null);

  const [isPlaying, setIsPlaying] = useState(false);
  const [isPaused, setIsPaused] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [audioGenerated, setAudioGenerated] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);

  // Timing refs
  const startTimeRef = useRef(0);
  const pausedTimeRef = useRef(0);

  const cleanupSource = useCallback(() => {
    if (sourceRef.current) {
      sourceRef.current.onended = null;
      sourceRef.current.stop();
      sourceRef.current = null;
    }
  }, []);

  const play = useCallback(
    async (buffer, offset) => {
      if (!audioContextRef.current) return;

      cleanupSource();

      const source = audioContextRef.current.createBufferSource();
      source.buffer = buffer;
      source.connect(audioContextRef.current.destination);
      sourceRef.current = source;

      source.onended = () => {
        if (sourceRef.current === source) {
          setIsPlaying(false);
          setIsPaused(false);
          pausedTimeRef.current = 0;
        }
      };

      source.start(0, offset);
      startTimeRef.current = audioContextRef.current.currentTime - offset;
      setIsPlaying(true);
      setIsPaused(false);
    },
    [cleanupSource]
  );

  const playAudio = useCallback(
    async (base64Audio) => {
      cleanupSource();

      if (!audioContextRef.current) {
        audioContextRef.current = new (window.AudioContext ||
          window.webkitAudioContext)({ sampleRate: 24000 });
      }
      const context = audioContextRef.current;

      if (context.state === "suspended") {
        await context.resume();
      }

      try {
        const decodedBytes = decode(base64Audio);
        const audioBuffer = await decodeAudioData(
          decodedBytes,
          context,
          24000,
          1
        );
        audioBufferRef.current = audioBuffer;
        pausedTimeRef.current = 0;
        setAudioGenerated(true);
        await play(audioBuffer, 0);
      } catch (error) {
        console.error("Failed to play audio:", error);
        setIsPlaying(false);
        setIsPaused(false);
        throw error;
      }
    },
    [play, cleanupSource]
  );

  const generateAndPlayAudio = useCallback(
    async (text, isAutoGeneration = false) => {
      if (!text) return;

      // Check if this is auto-generation and we've already auto-generated
      if (isAutoGeneration && autoGenerated) {
        return;
      }

      setIsGenerating(true);
      setAudioGenerated(false);

      try {
        // Clean the text for speech
        const cleanText = cleanMarkdownForSpeech(text);

        // Call the API to generate speech
        const response = await fetch("/api/generate/speech", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ text: cleanText }),
        });

        if (!response.ok) {
          throw new Error("Failed to generate speech");
        }

        const data = await response.json();

        if (data.audio) {
          await playAudio(data.audio);
          if (isAutoGeneration) {
            setAutoGenerated(true);
          }
        } else {
          throw new Error("No audio data received");
        }
      } catch (error) {
        console.error("Error generating or playing audio:", error);
        setIsGenerating(false);
        throw error;
      } finally {
        setIsGenerating(false);
      }
    },
    [playAudio, autoGenerated]
  );

  const pauseAudio = useCallback(() => {
    if (!isPlaying || !audioContextRef.current || !sourceRef.current) return;
    pausedTimeRef.current =
      audioContextRef.current.currentTime - startTimeRef.current;
    cleanupSource();
    setIsPlaying(false);
    setIsPaused(true);
  }, [isPlaying, cleanupSource]);

  const resumeAudio = useCallback(async () => {
    if (!isPaused || !audioBufferRef.current) return;
    await play(audioBufferRef.current, pausedTimeRef.current);
  }, [isPaused, play]);

  const resetAutoGenerated = useCallback(() => {
    setAutoGenerated(false);
  }, []);

  return {
    playAudio,
    generateAndPlayAudio,
    pauseAudio,
    resumeAudio,
    resetAutoGenerated,
    isPlaying,
    isPaused,
    isGenerating,
    audioGenerated,
    autoGenerated,
  };
};
